// <auto-generated />
using System;
using DctAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DctAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211115144014_Updates")]
    partial class Updates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DctApi.Shared.Models.DiaChiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Duong")
                        .HasColumnType("text");

                    b.Property<string>("QuanHuyen")
                        .HasColumnType("text");

                    b.Property<string>("SoNhaTo")
                        .HasColumnType("text");

                    b.Property<string>("TinhTP")
                        .HasColumnType("text");

                    b.Property<string>("XaPhuong")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiaChi");
                });

            modelBuilder.Entity("DctApi.Shared.Models.HinhAnhEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HinhAnh");
                });

            modelBuilder.Entity("DctApi.Shared.Models.HoSoShipperEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BHXMatSauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BHXMatTruocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLXHang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLXMatSauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLXMatTruocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLXSo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMNDMatSauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMNDMatTruocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CMNDNgayCap")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CMNDNoiCap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DiemBaiKiemTra")
                        .HasColumnType("numeric");

                    b.Property<string>("GiayDKXMatSauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GiayDKXMatTruocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GiayKiemTraXeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NamSxXe")
                        .HasColumnType("integer");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("text");

                    b.Property<string>("PhuongTienHinhDauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhuongTienHinhDuoiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BHXMatSauId");

                    b.HasIndex("BHXMatTruocId");

                    b.HasIndex("BLXMatSauId");

                    b.HasIndex("BLXMatTruocId");

                    b.HasIndex("CMNDMatSauId");

                    b.HasIndex("CMNDMatTruocId");

                    b.HasIndex("GiayDKXMatSauId");

                    b.HasIndex("GiayDKXMatTruocId");

                    b.HasIndex("GiayKiemTraXeId");

                    b.HasIndex("PhuongTienHinhDauId");

                    b.HasIndex("PhuongTienHinhDuoiId");

                    b.ToTable("HoSoShipper");
                });

            modelBuilder.Entity("DctApi.Shared.Models.KhachHangEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.ShipperEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DongXe")
                        .HasColumnType("text");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("DctApi.Shared.Models.TaiKhoanNganHangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("LienKet")
                        .HasColumnType("boolean");

                    b.Property<string>("MaNganHang")
                        .HasColumnType("text");

                    b.Property<string>("SoTK")
                        .HasColumnType("text");

                    b.Property<string>("TenChuTk")
                        .HasColumnType("text");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("text");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("TaiKhoanNganHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AvataIdId")
                        .HasColumnType("text");

                    b.Property<int?>("DiaChiIdId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvataIdId");

                    b.HasIndex("DiaChiIdId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DctApi.Shared.Models.HoSoShipperEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BHXMatSau")
                        .WithMany()
                        .HasForeignKey("BHXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BHXMatTruoc")
                        .WithMany()
                        .HasForeignKey("BHXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BLXMatSau")
                        .WithMany()
                        .HasForeignKey("BLXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BLXMatTruoc")
                        .WithMany()
                        .HasForeignKey("BLXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "CMNDMatSau")
                        .WithMany()
                        .HasForeignKey("CMNDMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "CMNDMatTruoc")
                        .WithMany()
                        .HasForeignKey("CMNDMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayDKXMatSau")
                        .WithMany()
                        .HasForeignKey("GiayDKXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayDKXMatTruoc")
                        .WithMany()
                        .HasForeignKey("GiayDKXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayKiemTraXe")
                        .WithMany()
                        .HasForeignKey("GiayKiemTraXeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "PhuongTienHinhDau")
                        .WithMany()
                        .HasForeignKey("PhuongTienHinhDauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "PhuongTienHinhDuoi")
                        .WithMany()
                        .HasForeignKey("PhuongTienHinhDuoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.KhachHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.ShipperEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.TaiKhoanNganHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.UserEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "AvataId")
                        .WithMany()
                        .HasForeignKey("AvataIdId");

                    b.HasOne("DctApi.Shared.Models.DiaChiEntity", "DiaChiId")
                        .WithMany()
                        .HasForeignKey("DiaChiIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
