// <auto-generated />
using System;
using DctAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DctAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211129031417_Update2")]
    partial class Update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DctApi.Shared.Models.CauHoiTracNghiemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CauHoiTracNghiem");
                });

            modelBuilder.Entity("DctApi.Shared.Models.ChiTietDonHangEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<int>("DonHangID")
                        .HasColumnType("integer");

                    b.Property<float>("KhoiLuong")
                        .HasColumnType("real");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.CuaHangEntity", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("LoaiCHID")
                        .HasColumnType("integer");

                    b.Property<string>("TenCuaHang")
                        .HasColumnType("text");

                    b.Property<bool>("TrangThaiKichHoat")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("UserID");

                    b.HasIndex("LoaiCHID");

                    b.HasIndex("UserEntityId");

                    b.ToTable("CuaHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.CuaHangSanPhamEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CuaHangID")
                        .HasColumnType("integer");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("CuaHangSanPham");
                });

            modelBuilder.Entity("DctApi.Shared.Models.DanhGiaEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DonHangID")
                        .HasColumnType("integer");

                    b.Property<int>("LoaiDGID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<int>("SoDiem")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("DonHangID");

                    b.HasIndex("LoaiDGID");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("DctApi.Shared.Models.DiaChiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Duong")
                        .HasColumnType("text");

                    b.Property<string>("QuanHuyen")
                        .HasColumnType("text");

                    b.Property<string>("SoNhaTo")
                        .HasColumnType("text");

                    b.Property<string>("TinhTP")
                        .HasColumnType("text");

                    b.Property<string>("XaPhuong")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiaChi");
                });

            modelBuilder.Entity("DctApi.Shared.Models.DonHangEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CuaHangID")
                        .HasColumnType("integer");

                    b.Property<int>("DiaChiGiaoId")
                        .HasColumnType("integer");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayMuaHang")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PTTTID")
                        .HasColumnType("integer");

                    b.Property<int>("ShipperID")
                        .HasColumnType("integer");

                    b.Property<int?>("TTDHID")
                        .HasColumnType("integer");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("DiaChiGiaoId");

                    b.HasIndex("PTTTID");

                    b.HasIndex("TTDHID");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.HinhAnhEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HinhAnh");
                });

            modelBuilder.Entity("DctApi.Shared.Models.HoSoShipperEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BHXMatSauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BHXMatTruocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLXHang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLXMatSauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLXMatTruocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BLXSo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMNDMatSauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMNDMatTruocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CMNDNgayCap")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CMNDNoiCap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DiemBaiKiemTra")
                        .HasColumnType("numeric");

                    b.Property<string>("GiayDKXMatSauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GiayDKXMatTruocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GiayKiemTraXeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NamSxXe")
                        .HasColumnType("integer");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("text");

                    b.Property<string>("PhuongTienHinhDauId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhuongTienHinhDuoiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BHXMatSauId");

                    b.HasIndex("BHXMatTruocId");

                    b.HasIndex("BLXMatSauId");

                    b.HasIndex("BLXMatTruocId");

                    b.HasIndex("CMNDMatSauId");

                    b.HasIndex("CMNDMatTruocId");

                    b.HasIndex("GiayDKXMatSauId");

                    b.HasIndex("GiayDKXMatTruocId");

                    b.HasIndex("GiayKiemTraXeId");

                    b.HasIndex("PhuongTienHinhDauId");

                    b.HasIndex("PhuongTienHinhDuoiId");

                    b.ToTable("HoSoShipper");
                });

            modelBuilder.Entity("DctApi.Shared.Models.KhachHangEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.LoaiCuaHangEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("LoaiCuaHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.LoaiDanhGiaEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("LoaiDanhGia");
                });

            modelBuilder.Entity("DctApi.Shared.Models.LoaiSanPhamEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("DctApi.Shared.Models.LuaChonTracNghiemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CauHoiId")
                        .HasColumnType("integer");

                    b.Property<bool>("Dung")
                        .HasColumnType("boolean");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.ToTable("LuaChonTracNghiem");
                });

            modelBuilder.Entity("DctApi.Shared.Models.NhaSanXuatEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DiaChiId")
                        .HasColumnType("integer");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("DiaChiId");

                    b.ToTable("NhaSanXuat");
                });

            modelBuilder.Entity("DctApi.Shared.Models.PhuongThucThanhToanEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("DctApi.Shared.Models.SanPhamEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("GiaSP")
                        .HasColumnType("real");

                    b.Property<string>("HinhSanPhamId")
                        .HasColumnType("text");

                    b.Property<int?>("LoaiSPID")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int?>("NSXID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("HinhSanPhamId");

                    b.HasIndex("LoaiSPID");

                    b.HasIndex("NSXID");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DctApi.Shared.Models.ShipperEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DongXe")
                        .HasColumnType("text");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("DctApi.Shared.Models.TaiKhoanNganHangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("LienKet")
                        .HasColumnType("boolean");

                    b.Property<string>("MaNganHang")
                        .HasColumnType("text");

                    b.Property<string>("SoTK")
                        .HasColumnType("text");

                    b.Property<string>("TenChuTk")
                        .HasColumnType("text");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("text");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("TaiKhoanNganHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.TrangThaiDonHangEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("TrangThaiDonHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AvataIdId")
                        .HasColumnType("text");

                    b.Property<int?>("DiaChiIdId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvataIdId");

                    b.HasIndex("DiaChiIdId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DctApi.Shared.Models.CuaHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.LoaiCuaHangEntity", "LoaiCH")
                        .WithMany()
                        .HasForeignKey("LoaiCHID");

                    b.HasOne("DctApi.Shared.Models.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.DanhGiaEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.DonHangEntity", "DonHang")
                        .WithMany()
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.LoaiDanhGiaEntity", "LoaiDG")
                        .WithMany()
                        .HasForeignKey("LoaiDGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.DonHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.DiaChiEntity", "DiaChiGiao")
                        .WithMany()
                        .HasForeignKey("DiaChiGiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.PhuongThucThanhToanEntity", "PTTT")
                        .WithMany()
                        .HasForeignKey("PTTTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.TrangThaiDonHangEntity", "TTDH")
                        .WithMany()
                        .HasForeignKey("TTDHID");
                });

            modelBuilder.Entity("DctApi.Shared.Models.HoSoShipperEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BHXMatSau")
                        .WithMany()
                        .HasForeignKey("BHXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BHXMatTruoc")
                        .WithMany()
                        .HasForeignKey("BHXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BLXMatSau")
                        .WithMany()
                        .HasForeignKey("BLXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BLXMatTruoc")
                        .WithMany()
                        .HasForeignKey("BLXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "CMNDMatSau")
                        .WithMany()
                        .HasForeignKey("CMNDMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "CMNDMatTruoc")
                        .WithMany()
                        .HasForeignKey("CMNDMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayDKXMatSau")
                        .WithMany()
                        .HasForeignKey("GiayDKXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayDKXMatTruoc")
                        .WithMany()
                        .HasForeignKey("GiayDKXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayKiemTraXe")
                        .WithMany()
                        .HasForeignKey("GiayKiemTraXeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "PhuongTienHinhDau")
                        .WithMany()
                        .HasForeignKey("PhuongTienHinhDauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "PhuongTienHinhDuoi")
                        .WithMany()
                        .HasForeignKey("PhuongTienHinhDuoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.KhachHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.LuaChonTracNghiemEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.CauHoiTracNghiemEntity", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.NhaSanXuatEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.DiaChiEntity", "DiaChi")
                        .WithMany()
                        .HasForeignKey("DiaChiId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.SanPhamEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "HinhSanPham")
                        .WithMany()
                        .HasForeignKey("HinhSanPhamId");

                    b.HasOne("DctApi.Shared.Models.LoaiSanPhamEntity", "LoaiSP")
                        .WithMany()
                        .HasForeignKey("LoaiSPID");

                    b.HasOne("DctApi.Shared.Models.NhaSanXuatEntity", "NSX")
                        .WithMany()
                        .HasForeignKey("NSXID");
                });

            modelBuilder.Entity("DctApi.Shared.Models.ShipperEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.TaiKhoanNganHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.UserEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "AvataId")
                        .WithMany()
                        .HasForeignKey("AvataIdId");

                    b.HasOne("DctApi.Shared.Models.DiaChiEntity", "DiaChiId")
                        .WithMany()
                        .HasForeignKey("DiaChiIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
