// <auto-generated />
using System;
using DctAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DctAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DctApi.Shared.Models.CauHoiTracNghiemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("CauHoiTracNghiem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NoiDung = "Sơ đồ nào sau đây phù hợp với thiết kế động?"
                        },
                        new
                        {
                            Id = 2,
                            NoiDung = "1+2=?"
                        },
                        new
                        {
                            Id = 3,
                            NoiDung = "Vai trò nào không có trong ĐI CHỢ THUÊ"
                        },
                        new
                        {
                            Id = 4,
                            NoiDung = "Trong sơ đồ class, quan hệ aggregration được thể hiện bằng"
                        },
                        new
                        {
                            Id = 5,
                            NoiDung = "Trong mô hình MVC, View đóng vai trò"
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.ChiTietDonHangEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<int>("DonHangID")
                        .HasColumnType("integer");

                    b.Property<float>("KhoiLuong")
                        .HasColumnType("real");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.CuaHangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int?>("LoaiCHId")
                        .HasColumnType("integer");

                    b.Property<string>("TenCuaHang")
                        .HasColumnType("text");

                    b.Property<bool>("TrangThaiKichHoat")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoaiCHId");

                    b.HasIndex("UserId");

                    b.ToTable("CuaHang");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenCuaHang = "Co-op Mart Cống Quỳnh",
                            TrangThaiKichHoat = true,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.CuaHangSanPhamEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("CuaHangID")
                        .HasColumnType("integer");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.ToTable("CuaHangSanPham");
                });

            modelBuilder.Entity("DctApi.Shared.Models.DanhGiaEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("DonHangId")
                        .HasColumnType("integer");

                    b.Property<int>("LoaiDGID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<int>("SoDiem")
                        .HasColumnType("integer");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.HasIndex("DonHangId");

                    b.HasIndex("LoaiDGID");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("DctApi.Shared.Models.DiaChiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Duong")
                        .HasColumnType("text");

                    b.Property<string>("QuanHuyen")
                        .HasColumnType("text");

                    b.Property<string>("SoNhaTo")
                        .HasColumnType("text");

                    b.Property<string>("TinhTP")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("XaPhuong")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiaChi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duong = "Cống Quỳnh",
                            QuanHuyen = "Quận 1",
                            SoNhaTo = "189C",
                            TinhTP = "TP. HCM",
                            XaPhuong = "Nguyễn Cư Trinh"
                        },
                        new
                        {
                            Id = 2,
                            Duong = "Nguyễn Văn Cừ",
                            QuanHuyen = "Quận 5",
                            SoNhaTo = "227",
                            TinhTP = "TP. HCM",
                            XaPhuong = "Phường 4"
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.DonHangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("CuaHangId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaChiGiaoId")
                        .HasColumnType("integer");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayMuaHang")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PTTTId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShipperId")
                        .HasColumnType("integer");

                    b.Property<int>("TTDHId")
                        .HasColumnType("integer");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("CuaHangId");

                    b.HasIndex("DiaChiGiaoId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("PTTTId");

                    b.HasIndex("ShipperId");

                    b.HasIndex("TTDHId");

                    b.ToTable("DonHang");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CuaHangId = 1,
                            DiaChiGiaoId = 2,
                            KhachHangId = 1,
                            NgayGiao = new DateTime(2021, 12, 20, 11, 53, 1, 271, DateTimeKind.Local).AddTicks(552),
                            NgayMuaHang = new DateTime(2021, 12, 20, 11, 53, 1, 272, DateTimeKind.Local).AddTicks(2297),
                            PTTTId = 1,
                            TTDHId = 2,
                            TongTien = 500000f
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.HinhAnhEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HinhAnh");
                });

            modelBuilder.Entity("DctApi.Shared.Models.HoSoShipperEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BHXMatSauId")
                        .HasColumnType("integer");

                    b.Property<int>("BHXMatTruocId")
                        .HasColumnType("integer");

                    b.Property<string>("BLXHang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BLXMatSauId")
                        .HasColumnType("integer");

                    b.Property<int>("BLXMatTruocId")
                        .HasColumnType("integer");

                    b.Property<string>("BLXSo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CMNDMatSauId")
                        .HasColumnType("integer");

                    b.Property<int>("CMNDMatTruocId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CMNDNgayCap")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CMNDNoiCap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<decimal?>("DiemBaiKiemTra")
                        .HasColumnType("numeric");

                    b.Property<int>("GiayDKXMatSauId")
                        .HasColumnType("integer");

                    b.Property<int>("GiayDKXMatTruocId")
                        .HasColumnType("integer");

                    b.Property<int>("GiayKiemTraXeId")
                        .HasColumnType("integer");

                    b.Property<int>("NamSXXe")
                        .HasColumnType("integer");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("text");

                    b.Property<int>("PhuongTienHinhDauId")
                        .HasColumnType("integer");

                    b.Property<int>("PhuongTienHinhDuoiId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("BHXMatSauId");

                    b.HasIndex("BHXMatTruocId");

                    b.HasIndex("BLXMatSauId");

                    b.HasIndex("BLXMatTruocId");

                    b.HasIndex("CMNDMatSauId");

                    b.HasIndex("CMNDMatTruocId");

                    b.HasIndex("GiayDKXMatSauId");

                    b.HasIndex("GiayDKXMatTruocId");

                    b.HasIndex("GiayKiemTraXeId");

                    b.HasIndex("PhuongTienHinhDauId");

                    b.HasIndex("PhuongTienHinhDuoiId");

                    b.ToTable("HoSoShipper");
                });

            modelBuilder.Entity("DctApi.Shared.Models.KhachHangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CMND = "123444222",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.KhoaDaoTaoEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("HuongDan")
                        .HasColumnType("text");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.ToTable("KhoaDaoTao");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            HuongDan = "Vui lòng xem video hướng dẫn để làm bài kiểm tra.",
                            NoiDung = "Khoá đào tạo shipper Đi Chợ Thuê",
                            URL = "www.google.com"
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.LoaiCuaHangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("LoaiCuaHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.LoaiDanhGiaEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.ToTable("LoaiDanhGia");
                });

            modelBuilder.Entity("DctApi.Shared.Models.LoaiSanPhamEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("DctApi.Shared.Models.LuaChonTracNghiemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CauHoiId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<bool>("Dung")
                        .HasColumnType("boolean");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.ToTable("LuaChonTracNghiem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CauHoiId = 1,
                            Dung = false,
                            NoiDung = "Class diagram"
                        },
                        new
                        {
                            Id = 2,
                            CauHoiId = 1,
                            Dung = true,
                            NoiDung = "Sequence diagram"
                        },
                        new
                        {
                            Id = 3,
                            CauHoiId = 1,
                            Dung = false,
                            NoiDung = "Use case diagram"
                        },
                        new
                        {
                            Id = 4,
                            CauHoiId = 1,
                            Dung = false,
                            NoiDung = "Package diagram"
                        },
                        new
                        {
                            Id = 5,
                            CauHoiId = 2,
                            Dung = false,
                            NoiDung = "1"
                        },
                        new
                        {
                            Id = 6,
                            CauHoiId = 2,
                            Dung = false,
                            NoiDung = "2"
                        },
                        new
                        {
                            Id = 7,
                            CauHoiId = 2,
                            Dung = true,
                            NoiDung = "3"
                        },
                        new
                        {
                            Id = 8,
                            CauHoiId = 2,
                            Dung = false,
                            NoiDung = "4"
                        },
                        new
                        {
                            Id = 9,
                            CauHoiId = 3,
                            Dung = false,
                            NoiDung = "Shipper"
                        },
                        new
                        {
                            Id = 10,
                            CauHoiId = 3,
                            Dung = false,
                            NoiDung = "Khách hàng"
                        },
                        new
                        {
                            Id = 11,
                            CauHoiId = 3,
                            Dung = true,
                            NoiDung = "Nhân viên kho"
                        },
                        new
                        {
                            Id = 12,
                            CauHoiId = 3,
                            Dung = false,
                            NoiDung = "Cửa hàng"
                        },
                        new
                        {
                            Id = 13,
                            CauHoiId = 4,
                            Dung = false,
                            NoiDung = "Mũi tên"
                        },
                        new
                        {
                            Id = 14,
                            CauHoiId = 4,
                            Dung = false,
                            NoiDung = "Đường nối"
                        },
                        new
                        {
                            Id = 15,
                            CauHoiId = 4,
                            Dung = false,
                            NoiDung = "Hình thoi đen"
                        },
                        new
                        {
                            Id = 16,
                            CauHoiId = 4,
                            Dung = true,
                            NoiDung = "Hình thoi trắng"
                        },
                        new
                        {
                            Id = 17,
                            CauHoiId = 5,
                            Dung = true,
                            NoiDung = "Gửi request đến và nhận response từ Controller"
                        },
                        new
                        {
                            Id = 18,
                            CauHoiId = 5,
                            Dung = false,
                            NoiDung = "Cập nhật giao diện"
                        },
                        new
                        {
                            Id = 19,
                            CauHoiId = 5,
                            Dung = false,
                            NoiDung = "Kiểm tra logic dữ liệu"
                        },
                        new
                        {
                            Id = 20,
                            CauHoiId = 5,
                            Dung = false,
                            NoiDung = "Lưu trữ dữ liệu vào database"
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.NhaSanXuatEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int?>("DiaChiId")
                        .HasColumnType("integer");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.HasIndex("DiaChiId");

                    b.ToTable("NhaSanXuat");
                });

            modelBuilder.Entity("DctApi.Shared.Models.PhuongThucThanhToanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ten = "Tiền mặt"
                        },
                        new
                        {
                            Id = 2,
                            Ten = "Thẻ ngân hàng"
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ten = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Ten = "Cửa Hàng"
                        },
                        new
                        {
                            Id = 3,
                            Ten = "Shipper"
                        },
                        new
                        {
                            Id = 4,
                            Ten = "Khách Hàng"
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.SanPhamEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<float>("GiaSP")
                        .HasColumnType("real");

                    b.Property<int?>("HinhSanPhamId")
                        .HasColumnType("integer");

                    b.Property<int?>("LoaiSPID")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int?>("NSXID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.HasIndex("HinhSanPhamId");

                    b.HasIndex("LoaiSPID");

                    b.HasIndex("NSXID");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DctApi.Shared.Models.ShipperEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("DongXe")
                        .HasColumnType("text");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shipper");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BienSo = "00A0-0000",
                            CMND = "000111222",
                            DongXe = "Honda Wave",
                            KichHoat = true,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.TaiKhoanNganHangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<bool>("LienKet")
                        .HasColumnType("boolean");

                    b.Property<string>("MaNganHang")
                        .HasColumnType("text");

                    b.Property<string>("SoTK")
                        .HasColumnType("text");

                    b.Property<string>("TenChuTk")
                        .HasColumnType("text");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int?>("UserEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("TaiKhoanNganHang");
                });

            modelBuilder.Entity("DctApi.Shared.Models.TrangThaiDonHangEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("TrangThaiDonHang");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ten = "Chờ xác nhận"
                        },
                        new
                        {
                            Id = 2,
                            Ten = "Cửa hàng đã xác nhận"
                        },
                        new
                        {
                            Id = 3,
                            Ten = "Đang lấy hàng"
                        },
                        new
                        {
                            Id = 4,
                            Ten = "Đang giao hàng"
                        },
                        new
                        {
                            Id = 5,
                            Ten = "Đã giao hàng"
                        },
                        new
                        {
                            Id = 6,
                            Ten = "Đã huỷ"
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("DiaChiId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("DiaChiId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChiId = 1,
                            Email = "cuahangcoop@email.com",
                            HoTen = "Cua Hang Co-op Mart",
                            MatKhau = "123456",
                            RoleId = 2,
                            SDT = "0123456789"
                        },
                        new
                        {
                            Id = 2,
                            DiaChiId = 2,
                            Email = "shipper@email.com",
                            HoTen = "Bùi Minh Quân",
                            MatKhau = "123456",
                            RoleId = 3,
                            SDT = "0123333444"
                        },
                        new
                        {
                            Id = 3,
                            DiaChiId = 2,
                            Email = "khachhangA@email.com",
                            HoTen = "Khách hàng A",
                            MatKhau = "123456",
                            RoleId = 4,
                            SDT = "0123123123"
                        });
                });

            modelBuilder.Entity("DctApi.Shared.Models.CuaHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.LoaiCuaHangEntity", "LoaiCH")
                        .WithMany()
                        .HasForeignKey("LoaiCHId");

                    b.HasOne("DctApi.Shared.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.DanhGiaEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.DonHangEntity", "DonHang")
                        .WithMany()
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.LoaiDanhGiaEntity", "LoaiDG")
                        .WithMany()
                        .HasForeignKey("LoaiDGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.DonHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.CuaHangEntity", "CuaHang")
                        .WithMany()
                        .HasForeignKey("CuaHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.DiaChiEntity", "DiaChiGiao")
                        .WithMany()
                        .HasForeignKey("DiaChiGiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.KhachHangEntity", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.PhuongThucThanhToanEntity", "PTTT")
                        .WithMany()
                        .HasForeignKey("PTTTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.ShipperEntity", "Shipper")
                        .WithMany()
                        .HasForeignKey("ShipperId");

                    b.HasOne("DctApi.Shared.Models.TrangThaiDonHangEntity", "TTDH")
                        .WithMany()
                        .HasForeignKey("TTDHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.HoSoShipperEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BHXMatSau")
                        .WithMany()
                        .HasForeignKey("BHXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BHXMatTruoc")
                        .WithMany()
                        .HasForeignKey("BHXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BLXMatSau")
                        .WithMany()
                        .HasForeignKey("BLXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "BLXMatTruoc")
                        .WithMany()
                        .HasForeignKey("BLXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "CMNDMatSau")
                        .WithMany()
                        .HasForeignKey("CMNDMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "CMNDMatTruoc")
                        .WithMany()
                        .HasForeignKey("CMNDMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayDKXMatSau")
                        .WithMany()
                        .HasForeignKey("GiayDKXMatSauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayDKXMatTruoc")
                        .WithMany()
                        .HasForeignKey("GiayDKXMatTruocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "GiayKiemTraXe")
                        .WithMany()
                        .HasForeignKey("GiayKiemTraXeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "PhuongTienHinhDau")
                        .WithMany()
                        .HasForeignKey("PhuongTienHinhDauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "PhuongTienHinhDuoi")
                        .WithMany()
                        .HasForeignKey("PhuongTienHinhDuoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.KhachHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.LuaChonTracNghiemEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.CauHoiTracNghiemEntity", "CauHoi")
                        .WithMany("DanhSachLuaChon")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.NhaSanXuatEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.DiaChiEntity", "DiaChi")
                        .WithMany()
                        .HasForeignKey("DiaChiId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.SanPhamEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "HinhSanPham")
                        .WithMany()
                        .HasForeignKey("HinhSanPhamId");

                    b.HasOne("DctApi.Shared.Models.LoaiSanPhamEntity", "LoaiSP")
                        .WithMany()
                        .HasForeignKey("LoaiSPID");

                    b.HasOne("DctApi.Shared.Models.NhaSanXuatEntity", "NSX")
                        .WithMany()
                        .HasForeignKey("NSXID");
                });

            modelBuilder.Entity("DctApi.Shared.Models.ShipperEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DctApi.Shared.Models.TaiKhoanNganHangEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("DctApi.Shared.Models.UserEntity", b =>
                {
                    b.HasOne("DctApi.Shared.Models.HinhAnhEntity", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.HasOne("DctApi.Shared.Models.DiaChiEntity", "DiaChi")
                        .WithMany()
                        .HasForeignKey("DiaChiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DctApi.Shared.Models.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
